### ISSUE TITLE
Boolean field compatibility issues

### ISSUE THREAD

**Issue by DarkSide666** [atk4/data#396] opened 2019-03-16 13:18 UTC
`addField('foo', ['type'=>'boolean', 'valueTrue'=>'Y', 'valueFalse'=>'N', 'default'='N'])` What values such field supposed to have.

 * what values can be `set()`
 * what values can be `get()`
 * how it should typecast when saving
 * how it should typecast when loading
 * will `if ($foo->get() === 'N')` still work ?

**Comment by romaninsh** [comment] 2019-03-18 12:51
related to #315

**Comment by romaninsh** [comment] 2019-03-18 12:51
@DarkSide666 if you could contribute test-cases for the above wrongdoings, it should be easier for me to fix.

**Comment by mvorisek** [comment] 2021-08-25 23:52
partly duplicate of https://github.com/atk4/data/issues/534

**Closed as completed by mvorisek** 2021-08-25 23:52 UTC
Labels: bug, BC-break
