### ISSUE TITLE
Implement field grouping for models

### ISSUE THREAD

**Issue by romaninsh** [atk4/data#358] opened 2018-11-21 16:27 UTC
See also: https://github.com/atk4/ui/pull/600

Currently, you can add as many fields as you want to the model:

``` php
$model->addField('name');
$model->addField('surname');
```

However, it would be nice if we could also group fields. For instance:

``` php
$model->addFieldGroup('full_name', ['name','surname']);
```

Here we define fields first and then group name. Here are just some things you can do with groups:

``` php
$model->addFieldGroup('full_name', ['name', 'surname'], ['Your Full Name', 'ui'=>['class'=>['red']]);
```

It should be even possible to use sub-groups:

``` php
$model->addFieldGroup('personal_information', ['full_name', 'address']);
```

In theory nesting could be as deep as you wish and field can also be part of multiple groups. Group should be unique and it's name should not be same as the field. Once group is defined, it can be used in setModel:

```
$form->setModel($user, ['personal_information']);
```

Instead of listing fields, specifying group will display all the fields in the group. The following rules will be respected:

 - if possible, fields will be laid out to respect the grouping. For instance first and last name will be on same line. full name and address will be grouped into sections.
 - group 'ui' property can suggest which layout to use for the form, pretty much same way how fields can use ui/form property.
 - it is a job of the UI element to understand and treat groups properly. If that's not being done and group name is passed to the Model (e.g. onlyfields etc) then fields will be replaced with all the fields it contains. That's to insure compatibility and simplify implementation for UI elements that are not recursive.
 - atk API, and export can also make use of grouping to group data, for instance get(['id', 'personal_information']) would return array with two elements, but second element would be array etc.

**Comment by DarkSide666** [comment] 2018-11-21 20:33
Sounds interesting, but definitely need to think more about this refactor / change.
I especially like `$form->setModel($user, ['group_name_here']);` part.
And ability to automatically set groups as form sections.

**Comment by romaninsh** [comment] 2018-11-21 22:54
See also: https://medium.com/@romaninsh/working-with-structured-form-data-d4a0e8b44b7e

**Comment by mvorisek** [comment] 2021-08-25 22:45
This is easily possible with SQL field with CONCAT expr

**Comment by DarkSide666** [comment] 2021-08-26 12:40
It's not about concating. It's more about grouping fields and use these group definitions in setModel afterwards.
```
$model->addFieldGroup('personal_info', ['full_name', 'address']);
$crud->setModel($model. ['personal_info']);
```
and this will add fields full_name and address as CRUD columns.
If these also are groups not single fields, then recursively nest until we get a list of included fields.

**Comment by mvorisek** [comment] 2021-08-26 12:54
please be more specific than `$model`, maybe simple example of data/usecase will help others to easily understand it

**Comment by DarkSide666** [comment] 2021-08-26 20:25
@romaninsh has described that very well 3 years ago (see above) with good example.

In short - that's ability to group model fields in some way (groups, collections, sets - call how you want).
That alone doesn't give any advantage to atk4/data, but can be nicely used in atk4/ui setModel() in case when you want to use only subset of all fields in form or CRUD and don't want to name all of the fields - just name field group.
And even better thig is that if in data model you add additional field in that field group then ui will automatically pick it up if it use setModel($model, ['field_group']) instead of naming all fields one by one directly in ui.

Surely this is not a bug. But it's quite good and useful feature in my opinion. And looks like it probably doesn't require to much changes in code (data and ui).

**Comment by mvorisek** [comment] 2021-08-26 20:26
I see, should be easy as virtual Field that will get/set the individual values. This way, it will work correctly also when nested.

**Comment by DarkSide666** [comment] 2021-08-26 20:32
What virtual field? Why virtual field? :)

```
// in data model
$this->addField('name');
$this->addField('surname');
$this->addFieldGroup('client_info', ['name','surname']);

// in ui
$form->setModel($model, ['client_info']);
// this will generate form with 2 fields - name and surname without exactly naming them

// now add in data model additional field and include it in field group
$this->addField('phone');
$this->addFieldGroup('client_info', ['name','surname','phone']); // replace previous addFieldGroup line

// no changes in ui needed and form will automatically show 3 fields now
```

**Comment by mvorisek** [comment] 2021-08-26 20:43
> atk API, and export can also make use of grouping to group data, for instance get(['id', 'personal_information']) would return array with two elements, but second element would be array etc.

I saw "API" and your example is for GUI. I understand what you mean, it is easy to implemente, but hard to understand, even more, because of the "group" kw which refers to something else in data (SQL GROUPing).

Yesterday, I purified the issues, I closed like 50 of them, which brought us here, but let's break up it here too, as this is a feature I do not want to implement nor strongly support. :)

**Comment by DarkSide666** [comment] 2021-08-26 20:49
Yeah, let's not close this. Maybe someday ...
We can call them _field sets_ maybe. `visible` and `editable` actually also can be field sets - set of visible fields and set of editable fields :)

Not sure about API - I found ui setModel() improvement a more useful.

**Comment by mvorisek** [comment] 2022-05-29 11:15
this is more like an ui feature and `Field::$ui` property can be used for it - just define key like `groupName` and display fields with the same name together

**Closed by mvorisek** 2022-05-29 11:15 UTC
Labels: enhancement, Saasty.io :building_construction:
