### ISSUE TITLE
add $caption, getModelCaption() and getTitle() 

### ISSUE THREAD

**Issue by romaninsh** [atk4/data#290] opened 2018-02-07 23:44 UTC
Currently atk4\ui\CRUD relies on a property `$m->title` where user can supposedly specify a different name of of the entire model. 

For example your "Client" model could have title="Klients" (for localization). In some cases you can specify a more meaningful title="Invoice to Payment association";

We need a more reliable and documented way to create model title/caption and somehow separate it from title of individual record (which as per #289 would use getTitle()). We also can't use `name` because it's used by container/trackable traits.

Here are some options:

 - getModelTitle
 - getModelName
 - getModelCaption
 - getCaption (my fav)
 - getModelDescription

Which do you think is the best method? Also to avoid confusion and distinguish $m->title from $m->title_field (because it does not relate to $m->id_field as $m->id), I suggest we also change the name of the property to $m->caption.

I'd like to hear which method name you would prefer. 

# CONCLUDED

```
$model->id_field = 'id'; // remains
$model->title_field; // 
$model->caption = 'Client Invoice'; // is added. Plain english.

$model->get('anyfield');
$model->getTitle(); // return value of $model[$model->title_field]. if not set, returns id. 
$model->getModelCaption(); // return (possibly localized) $model->caption.

**Comment by DarkSide666** [comment] 2018-02-08 12:50
This issue is duplicate of #289 ??

I think it should be like this:
* `$m->getTitle` = `$m->title`
* `$m->getRowTitle() = `$m->title_field && $m->hasElement($m->title_field) ? $m[$model->title_field] : $m->id`

If we have term `title` and `title_field` as properties (and can't change that to not break BC), then should use term `title` in method names too. Definitely not _caption_ or _description_ or something else - just _title_.

**Comment by romaninsh** [comment] 2018-02-12 22:08
Changing title is not BC. $title is not even defined.

**Comment by DarkSide666** [comment] 2018-02-13 19:14
but `title_field` is widely used in many models around :(

**Comment by romaninsh** [comment] 2018-02-14 09:33
$title_field yes. $title no.

**Comment by romaninsh** [comment] 2018-02-16 06:32
ok, let's agree on this:

``` php
$model->get('anyfield');
$model->getTitle(); // return $title_field 
$model->getModelCaption(); // return name of the model
```

no setters. No extra methods for ID (because we don't really need them).

**Comment by DarkSide666** [comment] 2018-02-16 17:07
"name of the model" is not the same as `$model->name` ,right? :)
It's new property of model? Let's call that property `$model->caption` ?

**Comment by romaninsh** [comment] 2018-02-20 13:01
correct. agree with caption.

**Comment by romaninsh** [comment] 2018-02-20 13:02
do you think $model->getModelCaption() would return a localized version of caption? (for 1.5)

**Comment by DarkSide666** [comment] 2018-02-20 20:29
I think it should return localized caption because caption is something we hard-code so there should be a way how to localize it.
Basically every string what is not user input or data from database should be localized.

**Closed** 2018-03-19 09:58 UTC
Labels: Consistency, enhancement, in progress
