### ISSUE TITLE
Model hasOne() results SQL with syntax error

### ISSUE THREAD

**Issue by enderlen** [atk4/data#515] opened 2020-02-26 10:01 UTC
hI,

I'm new with ATK4 and trying to implement my model:
```
CREATE TABLE "Patient" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"patientName"	TEXT NOT NULL,
	"patientEmail"	TEXT
)

class ModelPatient extends \atk4\data\Model{
	public $table = 'Extend1.Patient';
	function init() {
		parent::init();
		$this->description = "Patient";
		/* Basic grid fields */
		$this->addField('patientName',['caption'=>"Nom du patient",'required'=>true]);
		$this->addField('patientEmail',['type'=>'text','caption'=>'Email(s)']);
}

CREATE TABLE "Acte" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"patientId"	INTEGER NOT NULL,
	"acteName"	TEXT NOT NULL
)

class ModelActe extends \atk4\data\Model {
	public $table = 'Extend1.Acte';
	function init() {
		parent::init();
		$this->description = "Acte";
		/* Basic grid fields */
		$this->addField('acteName',['caption'=>'Acte','required'=>true]);
		// $this->hasOne('Patient',[new \MyApp\Models\ModelPatient($this->db),'our_field'=>'patientId','their_field'=>'id'])->addField('patientName');
}
```

I'm testing them using a Grid. It works well but as soon as I put the hasOne() relation between the 2 tables (above commented), it results an SQL query error:

> Stack Trace
> --
> 
> 33 | \app\vendor\atk4\dsql\src\Expression.php: 562 |   | prepare
>   | ( "select \"id\",\"acteName\",\"acteDate\",\"acteTypeId\",\"patientId\",(select \"patientName\" from \"Extend1\".\"Patient\" \"P\" where \"id\" = \"Extend1.Acte\".\"patientId\") \"patientName\" from \"Extend1\".\"Acte\" limit 0, 20")

And this is a real SQL query syntax error around the table name in "embedded" inner select:
`"select \"id\",\"acteName\",\"acteDate\",\"acteTypeId\",\"patientId\",(select \"patientName\" from \"Extend1\".\"Patient\" \"P\" where \"id\" = \"Extend1.Acte\".\"patientId\") \"patientName\" from \"Extend1\".\"Acte\" limit 0, 20"`
Correct SQL syntax should be:
`"select \"id\",\"acteName\",\"acteDate\",\"acteTypeId\",\"patientId\",(select \"patientName\" from \"Extend1\".\"Patient\" \"P\" where \"id\" = \"Extend1\".\".Acte\".\"patientId\") \"patientName\" from \"Extend1\".\"Acte\" limit 0, 20"`
So regarding SQL syntax, this means table name syntax is correct after last "from" in query (i.e.: **\\"Extend1\\".\\"Acte\\"**) but incorrect in the inner select (i.e.: **\\"Extend1.Acte\\"**).

Is there any workaround or way to fix that ?

**Comment by DarkSide666** [comment] 2020-02-26 10:07
$table should be 'Patient' not 'Extend1.Patient'.
It's not needed to add database name here. You specify database in DSN connection string only.

**Comment by enderlen** [comment] 2020-02-26 10:09
No, table name is 100% correct as I'm using an attached database.
Also it is working perfectly well displaying all data from the table in a Grid when hasOne() call is commented

**Comment by DarkSide666** [comment] 2020-02-26 10:11
Also (not a bug) I'm not sure why you're setting `$this->description` property. It's not one of atk4/data/Model properties. Maybe you're using it somewhere else - then fine. But then I would prefer to define it in class properties not in init method.

One more thing - use `::class` instead of actually creating new php object here:
```
$this->hasOne('Patient' [
    \MyApp\Models\ModelPatient::class,
    'our_field'=>'patientId',
    'their_field'=>'id',
])->addField('patientName');
```

**Comment by DarkSide666** [comment] 2020-02-26 10:13
Which DB engine you're using and what's _attached database_?

**Comment by enderlen** [comment] 2020-02-26 10:18
sqlite

**Comment by enderlen** [comment] 2020-02-26 10:20
https://www.tutorialspoint.com/sqlite/sqlite_attach_database.htm

**Comment by DarkSide666** [comment] 2020-02-26 10:39
OK I see. I didn't expect to have dot in table names. This will need to be fixed in atk4/data I guess.

**Comment by enderlen** [comment] 2020-02-26 10:41
Ok thks for your help!

**Comment by DarkSide666** [comment] 2020-02-26 10:41
As a workaround I guess you can try setting `$table_alias` property of model to something simple (without dots).

**Closed** 2020-03-09 20:33 UTC
Labels: bug, question
